### ISSUE TITLE
Support for argument names

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr#58]
This might be a stretch but **if** tealr gets re-written, it might be useful to add functionality supporting custom parameter names for methods/functions.

This is especially useful if a method accepts many parameters all of the same type:
```rust
|_,_,(x,y,z) : (f32,f32,f32)|
```
for example.

This could be supported by generating and parsing special syntax into the markdown perhaps like:

```markdown
Args:
- x: the x value
- y: the y value
- z: the z value
```

**Comment by lenscas** [comment]
I would love to add this, but I have no idea how I would do this in a way that doesn't add a lot of redundancy when adding methods or forces people to write inside a proc macro.

.d.tl.files also already support named arguments so the documentation could just use that syntax as well....

**Comment by makspll** [comment]
This might be a good argument for converting to a macro then haha,
The question is if it's good enough

**Comment by lenscas** [comment]
Actually, doesn't mlua and rlua have a 'fromLuaMulti' trait? If so, a simple macro_rules can be used to allow quick creation of a new type that implements TypeName and FromLuaMulti + whatever else is needed. The typename can lay the full name out like `paramName :   typeName, secondParam : SecondType`  and I think everything will end up working
