### ISSUE TITLE
alpha3 release doesn't add `tealr_version_used` to the generated json 

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr#72]
As in title, changes since the release I believe fix this but currently if you use the alpha3 versions of both this and the `tealr_doc_gen` package the json format is incompatible I believe

**Comment by lenscas** [comment]
yea, I'm currently working on deprecating the `.generate` methods in tealr, with the correct changes in the documentation to reflect that and to then push a fourth alpha before yanking the alpha3 builds.

**Comment by lenscas** [comment]
tealr version 0.9.0-alpha4 and tealr_doc_gen version 0.3.0-alpha2 got released which should have fixed this problem.

**Comment by makspll** [comment]
fantastic, thanks!
