### ISSUE TITLE
Question: Which version of teal to pin against

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr#85]
Hi I am in the process of upgrading to the new tealr/mlua versions, previously I had to pin the teal version to avoid issues, which version should I pin against for this release?

**Comment by lenscas** [comment]
I didn't update any syntax that gets spit out nor did any work on the macro's that interact with the teal compiler. So, whatever version of teal you had been using should still work.

Ideally, newer versions should also work but I did not have time to check that.

**Comment by makspll** [comment]
Got you! Lovely, and no worries!
